name: Publish docs via GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Install asdf
        uses: asdf-vm/actions/setup@v1
      - name: Cache asdf tools
        uses: actions/cache@v2
        with:
          path: |
            /home/runner/.asdf
          key: ${{ runner.os }}-${{ hashFiles('**/.tool-versions') }}

      - name: Install required tools
        run: |
          asdf plugin-add mongodb https://github.com/junminahn/asdf-mongodb.git || true
          cat .tool-versions | cut -f 1 -d ' ' | xargs -n 1 asdf plugin-add || true
          asdf plugin-update --all
          asdf install
          asdf reshim

      - name: Install python tools
        run: |
          pip install -r requirements.txt
          asdf reshim

      - name: Build the MkDocs site
        run: |
          make mk_build

      - name: Attach SSH Private Key
        uses: junminahn/action-ssh@v0.2.0
        with:
          encryption_key: ${{ secrets.ENCRYPTION_KEY }}

      - name: Push the MkDocs site
        run: |
          rm -rf .git
          cd site
          touch .nojekyll
          git init
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config commit.gpgsign false
          git add .
          git commit -m "deploy MkDocs site to github pages"
          git branch -M gh-pages
          git push --force --quiet git@github.com:express-toolkit/express-toolkit.github.io.git gh-pages

      # - name: Deploy docs
      #   uses: mhausenblas/mkdocs-deploy-gh-pages@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     CONFIG_FILE: mkdocs.yml
      #     REQUIREMENTS: requirements.txt
